### ISSUE TITLE
[Bug] Crash when the goblin eats food.

### ISSUE THREAD

**Issue by Khytwel** [Jab125/goblin-traders-fabric#37]
### Minecraft Username

Khytwel

### Version

latest commit

### Minecraft Version

1.18.*

### What did you expect?

Let him eat peacefully without making us crash :)

### What did you get?

https://gist.github.com/Khytwel/7f4dd435742fe1f2b791c569e102e6c5

**Comment by Jab125** [comment]
seems like a mod conflict, can you run it with just goblin traders, thonkutil 2.7.0, cloth config, and FAPI?

**Comment by Khytwel** [comment]
Well, there are no more crashs after some tests. Thanks anyway.

**Comment by marewey** [comment]
Still getting this error. I can post a crash report. What did you do to fix this?

**Comment by marewey** [comment]
Description: Ticking entity

java.lang.ClassCastException: class net.hat.gt.entities.VeinGoblinTraderEntity cannot be cast to class net.minecraft.class_1657 (net.hat.gt.entities.VeinGoblinTraderEntity and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @60addb54)
	at net.minecraft.class_1799.handler$bbk000$finishUsingItem(class_1799.java:1141)
	at net.minecraft.class_1799.method_7910(class_1799.java)
	at net.hat.gt.entities.AbstractGoblinEntity.method_6040(AbstractGoblinEntity.java:149)
	at net.minecraft.class_1309.method_37119(class_1309.java:2959)
	at net.minecraft.class_1309.method_6076(class_1309.java:2946)
	at net.minecraft.class_1309.method_5773(class_1309.java:2312)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.hat.gt.entities.AbstractGoblinEntity.method_5773(AbstractGoblinEntity.java:369)
	at net.hat.gt.entities.VeinGoblinTraderEntity.method_5773(VeinGoblinTraderEntity.java:55)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.redirect$bad000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4750)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.handler$zjb000$modifiedRunLoop(MinecraftServer.java:3856)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Jab125** [comment]
Can you post the entire crash report as a FILE?

**Comment by marewey** [comment]
[crash-2022-02-23_03.26.29-server.txt](https://github.com/3e2j/goblin-traders-fabric/files/8129054/crash-2022-02-23_03.26.29-server.txt)

Yes, here ya go. The Update Supressed has been turned off, but it does seem to stick around, but even with that mod removed, it still was having the same issue.

**Comment by marewey** [comment]
Any news on an update? Otherwise I think I might need to stop playing with this mod. lol. crashes are getting more and more frequent

**Comment by Jab125** [comment]
I believe it is a mod conflict, so it will be a while before I can find the conflicting mod.

**Comment by Jab125** [comment]
@marewey try to figure out what mod is causing it by uninstalling 50% of your mods and seeing if the issue persists

when you uninstall half of the mods, if the crashing stops, then one of the mods you've uninstalled was causing the crash.

Repeat this until you've identified what the mods are

(don't uninstall cloth config, goblin traders, or thonkutil)

**Comment by mizumio** [comment]
Sorry, because my English is not good, I used a translator to write this message.

**Version:**
iris-mc1.18.1-1.2.0-pre
modmenu-3.0.1
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
fabric-api-0.46.4+1.18
cloth-config-6.2.57-fabric
thonkutil-2.8.0-alpha.2+1.18
goblin-traders-1.5
end-goblin-traders-1.4.2
_**collective-fabric-1.18.x-4.8**_

**Minecraft Version:**
1.18.1

**List of mods used:**
https://docs.google.com/document/d/112bx42z7VLBXwPPpvhgf5OPzhPbqbjTpdjwlPGQmjoQ/edit

**Question:**
After installing "**Collective (Fabric)**", both Goblins and Wandering Trader in vanilla Minecraft will crash the game after eating.

Collective (Fabric) URL：
https://www.curseforge.com/minecraft/mc-mods/collective-fabric

Crash report：
[crash-2022-03-03_06.31.29-server.txt](https://github.com/3e2j/goblin-traders-fabric/files/8173373/crash-2022-03-03_06.31.29-server.txt)

**Comment by Jab125** [comment]
Then open an issue in collective

**Comment by mizumio** [comment]
Okay, thank you for taking the time to respond to me.
This is my first time using GitHub to report these types of issues, so I'm not sure where to report them.
This mod is really cute, so I would really like to keep both the Goblin and Collective mods to play together! (●'◡'●)ﾉ♥

**Comment by Jab125** [comment]
Update collective to the latest version
